### ISSUE TITLE
milestone1: 2019.08.23 - 13.07.2020

### ISSUE THREAD

**Issue by serapath** [datdotorg/website#1]
## `@todo` [milestone1: 2019.08.23 - 13.07.2020](https://github.com/playproject-io/datdot-application-2019-11-25/blob/master/milestone-1-report.md)
* [x] **[`datdot#4` 2019.08.23-2019.08.24 | p2p hosting jam :-)](https://github.com/playproject-io/datdot/issues/4)**
* [x] [`datdot#8` spec: write down p2p hosting idea](https://github.com/playproject-io/datdot/issues/8)
* [x] add more todo's :D
* [x] get access to the underlying hypercores of the archive (to get the root)
* [x] figure out why @polkadot/api doesn't work properly
* [x] [`datdot#9` spec: summarize idea to prepare for grant](https://github.com/playproject-io/datdot/issues/9)
* [x] **[`datdot#7` spec: apply & submit for web3 foundation grant](https://github.com/playproject-io/datdot/issues/7)**
* [x] build/assemble team
* [x] [`datdot#10` spec: refine datdot specification](https://github.com/playproject-io/datdot/issues/10)
* [x] [`datdot#11` spec: formalize datdot specification](https://github.com/playproject-io/datdot/issues/11)
* [x] [`datdot#12` 2019.10.15 | email thread with @okdistribute](https://github.com/playproject-io/datdot/issues/12)
* [x] **[`datdot#5` 2019.10.14,2019.10.16 | osaka datdot jam](https://github.com/playproject-io/datdot/issues/5)**
* [x] [`datdot#26` 2019.10.21 | video call with @okdistribute and @RangerMauve from the datproject](https://github.com/playproject-io/datdot/issues/26)
* [x] [`datdot#13` 2019.10.29 | video call with @RangerMauve](https://github.com/playproject-io/datdot/issues/13)
* [x] [`datdot#19` spec: summarize current spec](https://github.com/playproject-io/datdot/issues/19)
* [x] [`datdot#20` spec: formalize summary spec of datdot](https://github.com/playproject-io/datdot/issues/20)
* [x] [`datdot#21` spec: prepare spec after merge of grant pull request](https://github.com/playproject-io/datdot/issues/21)
* [x] **[`datdot#15` 2019.12.06-12:00pm UTC-0 | play partner meeting](https://github.com/playproject-io/datdot/issues/15)**
* [x] **[`datdot#18` 2019.12.26-12:00pm UTC-0 | play partner meeting ](https://github.com/playproject-io/datdot/issues/18)**
* [x] **[`datdot#17` 2020.01.07-12:00pm UTC-0 | play partner meeting](https://github.com/playproject-io/datdot/issues/17)**
* [x] **[`datdot#3` 2020.01.14-12:00pm UTC-0 | weekly partner meeting](https://github.com/playproject-io/datdot/issues/3)**
* [x] **[`datdot#25` 2020.01.21-08:00pm UTC-0 | weekly partner meeting](https://github.com/playproject-io/datdot/issues/25)**
* [x] **[`datdot#27` 2020.02.04-08:00pm UTC-0 | next datdot sync](https://github.com/playproject-io/datdot/issues/27)**
* [x] **[`datdot#28` 2020.02.11-08:00pm UTC-0 | datdot sync](https://github.com/playproject-io/datdot/issues/28)**
* [x] choose logo
  * ~~[inspiration1](https://www.youtube.com/watch?time_continue=15&v=f5o1p0WK0JE)~~
  * ~~[inspiration2](https://i1.wp.com/www.lataco.com/wp-content/uploads/die_la_die_13.jpg?zoom=2.25&resize=750%2C670&ssl=1)~~
  * ~~[inspiration3](https://datdot.bigcartel.com/)~~
* [x] **[`datdot#30` 2020.02.18-08:00pm UTC-0 | datdot sync](https://github.com/playproject-io/datdot/issues/30)**
* [x] **[`datdot#31` 2020.02.25-08:00pm UTC-0 | datdot sync](https://github.com/playproject-io/datdot/issues/31)**
* [x] [`datdot#36` 2020.02.27-17:00pm UTC-0 | dat comm comm call](https://github.com/playproject-io/datdot/issues/36)
* [x] **[`datdot#35` 2020.03.03-06:00am UTC-0 | datdot sync](https://github.com/playproject-io/datdot/issues/35)**
* [x] **~~[`datdot#42` 2020.03.10-19:00Z (=UTC-0) | datdot sync | CANCELED](https://github.com/playproject-io/datdot/issues/42)~~**
* [x] **[`datdot#43` 2020.03.17-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/43)**
* [x] [`datdot-research#9` 2020.03.23-08:00am | consult with mafintosh](https://github.com/playproject-io/datdot-research/issues/9)
* [x] **[`datdot#44` 2020.03.24-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/44)**
* [x] **[`datdot#46` 2020.03.31-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/46)**
* [x] **[`datdot#47` 2020.04.07-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/47)**
* [x] **[`datdot#48` 2020.04.14-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/48)**
* [x] **[`datdot#50` 2020.04.21-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/50)**
* [x] **[`datdot#49` 2020.04.28-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/49)**
* [x] clean up repos a bit and bring issues up2date and relate them
* [x] **[`datdot#51` 2020.05.05-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/51)**
* [x] **[`datdot#55` 2020.05.12-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/55)**
* [x] **[`datdot#61` 2020.05.19-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/61)**
* [x] **[`datdot#62` 2020.05.26-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/62)**
* [x]  **[`datdot#63` 2020.06.02-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/63)**
* [x] **[`datdot#64` 2020.06.09-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/64)**
* [x] **[`datdot#65` 2020.06.16-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/65)**
* [x] [`datdot#34` plan datdot presentation event](https://github.com/playproject-io/datdot/issues/34)
* [x] [`datdot#37` 2020.04.29-2020.07.30 | dat consortium call](https://github.com/playproject-io/datdot/issues/37)
* [x] **[`datdot#66` 2020.08.11-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/66)**

---
**future roadmapping:**
* [`datdot#71` milestone 2](https://github.com/playproject-io/datdot/issues/71)
* [`datdot#69` milestone 3](https://github.com/playproject-io/datdot/issues/69)
* [`datdot#70` backlog](https://github.com/playproject-io/datdot/issues/70)

**Comment by serapath** [comment]
### [x] milestone1
* [x] **[`datdot#4` 2019.08.23-2019.08.24 | p2p hosting jam :-)](https://github.com/playproject-io/datdot/issues/4)**
* [x] [`datdot#8` spec: write down p2p hosting idea](https://github.com/playproject-io/datdot/issues/8)
* [x] add more todo's :D
* [x] get access to the underlying hypercores of the archive (to get the root)
* [x] figure out why @polkadot/api doesn't work properly
* [x] [`datdot#9` spec: summarize idea to prepare for grant](https://github.com/playproject-io/datdot/issues/9)
* [x] **[`datdot#7` spec: apply & submit for web3 foundation grant](https://github.com/playproject-io/datdot/issues/7)**
* [x] build/assemble team
* [x] [`datdot#10` spec: refine datdot specification](https://github.com/playproject-io/datdot/issues/10)
* [x] [`datdot#11` spec: formalize datdot specification](https://github.com/playproject-io/datdot/issues/11)
* [x] [`datdot#12` 2019.10.15 | email thread with @okdistribute](https://github.com/playproject-io/datdot/issues/12)
* [x] **[`datdot#5` 2019.10.14,2019.10.16 | osaka datdot jam](https://github.com/playproject-io/datdot/issues/5)**
* [x] [`datdot#26` 2019.10.21 | video call with @okdistribute and @RangerMauve from the datproject](https://github.com/playproject-io/datdot/issues/26)
* [x] [`datdot#13` 2019.10.29 | video call with @RangerMauve](https://github.com/playproject-io/datdot/issues/13)
* [x] [`datdot#19` spec: summarize current spec](https://github.com/playproject-io/datdot/issues/19)
* [x] [`datdot#20` spec: formalize summary spec of datdot](https://github.com/playproject-io/datdot/issues/20)
* [x] [`datdot#21` spec: prepare spec after merge of grant pull request](https://github.com/playproject-io/datdot/issues/21)
* [x] **[`datdot#15` 2019.12.06-12:00pm UTC-0 | play partner meeting](https://github.com/playproject-io/datdot/issues/15)**
* [x] **[`datdot#18` 2019.12.26-12:00pm UTC-0 | play partner meeting ](https://github.com/playproject-io/datdot/issues/18)**
* [x] **[`datdot#17` 2020.01.07-12:00pm UTC-0 | play partner meeting](https://github.com/playproject-io/datdot/issues/17)**
* [x] **[`datdot#3` 2020.01.14-12:00pm UTC-0 | weekly partner meeting](https://github.com/playproject-io/datdot/issues/3)**
* [x] **[`datdot#25` 2020.01.21-08:00pm UTC-0 | weekly partner meeting](https://github.com/playproject-io/datdot/issues/25)**
* [x] **[`datdot#27` 2020.02.04-08:00pm UTC-0 | next datdot sync](https://github.com/playproject-io/datdot/issues/27)**
* [x] **[`datdot#28` 2020.02.11-08:00pm UTC-0 | datdot sync](https://github.com/playproject-io/datdot/issues/28)**
* [x] choose logo
  * ~~[inspiration1](https://www.youtube.com/watch?time_continue=15&v=f5o1p0WK0JE)~~
  * ~~[inspiration2](https://i1.wp.com/www.lataco.com/wp-content/uploads/die_la_die_13.jpg?zoom=2.25&resize=750%2C670&ssl=1)~~
  * ~~[inspiration3](https://datdot.bigcartel.com/)~~
* [x] **[`datdot#30` 2020.02.18-08:00pm UTC-0 | datdot sync](https://github.com/playproject-io/datdot/issues/30)**
* [x] **[`datdot#31` 2020.02.25-08:00pm UTC-0 | datdot sync](https://github.com/playproject-io/datdot/issues/31)**
* [x] [`datdot#36` 2020.02.27-17:00pm UTC-0 | dat comm comm call](https://github.com/playproject-io/datdot/issues/36)
* [x] **[`datdot#35` 2020.03.03-06:00am UTC-0 | datdot sync](https://github.com/playproject-io/datdot/issues/35)**
* [x] **~~[`datdot#42` 2020.03.10-19:00Z (=UTC-0) | datdot sync | CANCELED](https://github.com/playproject-io/datdot/issues/42)~~**
* [x] **[`datdot#43` 2020.03.17-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/43)**
* [x] [`datdot-research#9` 2020.03.23-08:00am | consult with mafintosh](https://github.com/playproject-io/datdot-research/issues/9)
* [x] **[`datdot#44` 2020.03.24-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/44)**
* [x] **[`datdot#46` 2020.03.31-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/46)**
* [x] **[`datdot#47` 2020.04.07-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/47)**
* [x] **[`datdot#48` 2020.04.14-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/48)**
* [x] **[`datdot#50` 2020.04.21-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/50)**
* [x] **[`datdot#49` 2020.04.28-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/49)**
* [x] clean up repos a bit and bring issues up2date and relate them
* [x] **[`datdot#51` 2020.05.05-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/51)**
* [x] **[`datdot#55` 2020.05.12-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/55)**
* [x] **[`datdot#61` 2020.05.19-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/61)**
* [x] **[`datdot#62` 2020.05.26-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/62)**
* [x]  **[`datdot#63` 2020.06.02-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/63)**
* [x] **[`datdot#64` 2020.06.09-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/64)**
* [x] **[`datdot#65` 2020.06.16-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/65)**
* [x] [`datdot#66` 2020.08.11-19:00Z (=UTC-0) | datdot sync](https://github.com/playproject-io/datdot/issues/66)
