### ISSUE TITLE
datdot project landing page

### ISSUE THREAD

**Issue by serapath** [datdotorg/website#2]
## `@todo`
* ~~add temporary website with a button to datdot twitter called `subscribe to updates`~~
* [x] make landing page layout for datdot landingpage for users to learn about the project and download the app
    * see https://beakerbrowser.com/
    * https://brave.com/
    * https://www.google.ca/chrome/
    * https://www.telegram.org/
    * https://www.whatsapp.com/
    * any other simple downoad app pages
    * think about offering: email subscriptions (e.g. for new release notifications)
* [x] make moodboard to decide about the style
    * see `inspiration` below to make a https://www.pinterest.com mood board
    * we probably need 3-4 iterations
    * nina: https://www.pinterest.de/ninabreznik/datdot/
    * alex: ...
    * fiona: ...
* [x] for languages maybe use `language icon` + `language code`
    * http://www.mathguide.de/info/tools/languagecode.html
* [x] **task bar** inspiration
    * https://www.computerhope.com/jargon/t/windows-taskbars.jpg
    * https://www.computerhope.com/jargon/t/windows-taskbar.jpg
* [x] move the TASK BAR on the bottom
* [x] add clock to the TASK BAR
* [x] PROFILE 
    - [x] icon + sign in, 
    - ~~datdot icon + settings~~
* [x] SHOW DESKTOP button
* [x] ADD MINIMIZE
    - show window buttons on TASK BAR
* [x] NOTIFICATIONS
    - group read and unread
* [x] START BUTTON (Datdot icon)
    - DOCUMENTATION
    - INSTALLER 
    - MISC 
      - pacman 
      - coding game 
    - HELP 
      - support chat 
      - about
* [x] THEMES
    - make blue text on dark background more readable
* [x] avatar not in start menu
* [ ] run input field with autocomplete in start menu
* [ ] settings in user account under DATDOT
* [ ] APPEARANCE
    1. Have one white/empty/default theme with minimal size (in kb)
        * no custom font
        * no images
        * etc...
* [x] On Desktop: rename "Installer.exe" to "Datdot.install"
* [ ] use moodboard style to implement the website with the layout we decided upon
* [ ] specify text and other content to fill the landingpage
* [ ] [`playproject-io.github.io#14` package manager input field & related](https://github.com/playproject-io/playproject-io.github.io/issues/14)

---

**DIFFERENCE**
  * **OLD WORLD:**
    1. Big Operating System Installation (e.g. 1 GB)
    2. Settings (ENABLE/INSTALL/DISABLE/UNINSTALL)
    3. App Store
        * App
        * Settings
  * **NEW WORLD:** ("Datdot Apps")
    2. Website Sized Operating System Installation (e.g. 1-2 MB)
        - offline first websites/apps
        * APPS: (Pac man, CodingGame, Cabal, Mapeo, DatExplorer)

**Comment by fionataeyang** [comment]
Update 5.20.2020
### [Wireframe v8](https://xd.adobe.com/view/75dfc471-d32f-4517-4865-76e6feaeda41-03ee/)

Update 5.6.2020
[Wireframe v7](https://xd.adobe.com/view/2639eefa-6391-4861-74d3-ebfbe6732db9-5008/)

Update: 4.25.2020
[Wireframe v6](https://xd.adobe.com/view/05dbcab2-a938-422c-717c-063a65e9847c-73ea/)

Update: 4.14.2020
[Wireframev 5](https://xd.adobe.com/view/e7a505be-1e7e-4b5e-4d18-866825368100-9194/)
- change task bar to bottom
- add sign in, adjust sign out for user profile
- add launch menu
- adjust icon direction
- add clock
- change dropdown menu to dropup menu
- make welcome
- add .exe, .html for the icon's name to better recognize
- make show desktop button
- make quick launch bar
- adjust prototype links
--------------------------------------------------------------------------------------------
Update: 4.5.2020
[Wireframe v4](https://xd.adobe.com/view/0c9772b4-d652-4e59-414a-3b2dc88ea170-7aa6/)
- add avatar
- add notification
- add avatar dropdown
- delete other icons on the desktop, only Doc, Installer, Misc, Chat. 
- add download button in the document
- add release notes in document
--------------------------------------------------------------------------------------------
[Wireframe v3](https://xd.adobe.com/view/35f8a3cb-c745-4b65-751f-fff72837cad1-43c9/) (3.26.2020)
[Wireframe v2](https://xd.adobe.com/view/59270f91-41dd-4e86-7a9d-d9ef95e9d290-2f16/) (3.17.2020)
[Wireframe v1](https://xd.adobe.com/view/be1fd832-0e40-4e50-7f8a-432792fbafc5-c82e/)  
[Wireframe](https://xd.adobe.com/view/f6135776-58e1-4820-9777-68520fb2ac1e-a340/) (3.4.2020)

**Comment by fionataeyang** [comment]
# Design soucres
### Animated gif
https://www.animatedimages.org/
http://bestanimations.com/
https://www.fg-a.com/
http://www.free-web-animations.com/
https://gifer.com/en/

### Images
http://clipartmag.com/
https://www.kindpng.com/
https://www.fg-a.com/
https://www.1001freedownloads.com/
https://teamcfadvance.org/
https://www.pngfuel.com/

### Icons
https://findicons.com
http://www.iconarchive.com/

**Comment by fionataeyang** [comment]
Update: 4.8.2020
### new Mockups
[demo4](https://xd.adobe.com/view/8ff62100-4756-479f-5e7c-4da70227e100-f9c7/)


Update: 4.1.2020
[demo3](https://xd.adobe.com/view/da695a7c-69b0-4b8b-54cd-f4c66764e1a5-ac58/)
Update: 3.18.2020
### old Mockups for home
[demo2](https://xd.adobe.com/view/2ee9fe5f-af8f-4722-590a-655301e32456-58d8/)
[demo1](https://xd.adobe.com/view/baa1fc77-0eef-4f78-47df-a833aaa1aa20-cc90/)

**Comment by serapath** [comment]
for languages maybe use `language icon` + `language code`
* http://www.mathguide.de/info/tools/languagecode.html

**Comment by ninabreznik** [comment]
**Inspiration:**
* fantastic concept http://www.purchase.design/
* subtle patterns
    * https://www.heropatterns.com/
    * http://thepatternlibrary.com/
    * https://www.transparenttextures.com/
* [some search results](https://www.google.com/search?q=diy+computer+scene+90s&tbm=isch&ved=2ahUKEwjhjNic5u7nAhUChp4KHX6mCAIQ2-cCegQIABAA&oq=diy+computer+scene+90s&gs_l=img.3...42567.49317..49440...1.0..0.82.1493.23......0....1..gws-wiz-img.......35i39j0j0i67j0i8i30j0i24.RQhQ74Q1joo&ei=LSxWXqHCEYKM-gT-zKIQ&bih=952&biw=1920)
* https://www.youtube.com/watch?v=ff1qyr6hTgM
* https://www.creativebloq.com/features/are-brutalist-sites-the-webs-punk-rock-moment
* https://medium.com/@xtianmiller/how-to-brutalize-the-web-e06b22f7de57
* http://eeerik.com/
* https://www.awwwards.com/sites/the-website-of-erik-bernacchi
* [google search](https://www.google.com/imgres?imgurl=https://pmcvariety.files.wordpress.com/2017/10/professor.jpg?w%3D1000%26h%3D563%26crop%3D1&imgrefurl=https://variety.com/2017/film/festivals/lumiere-festival-gertie-the-dinosaur-professor-balthazar-reanimated-1202594148/&tbnid=T4SEzdAcVRZPQM&vet=1&docid=gC75qm40JfkzSM&w=1000&h=563&itg=1&q=baltazar+cartoon&source=sh/x/im)
* https://twitter.com/DatDotOrg/status/1227097089261178881
* [another google search](https://www.google.com/imgres?imgurl=https://i.pinimg.com/originals/65/85/93/658593da97a630d5d80923951e380284.jpg&imgrefurl=https://www.pinterest.com/pin/351210470926648308/&tbnid=axIditDQ1H5zNM&vet=1&docid=MPu-EI5ymTuYoM&w=2560&h=2800&q=retro+brutalist+web+design&source=sh/x/im)
* https://www.kickscondor.com
* https://spacemesh.io/team/
* https://www.instagram.com/mollyccostello/
* https://joinsunshine.com/#trust
* https://q9f.cc/
* https://spacejam.com/jam.htm
* https://gizmodo.com/remember-the-hilarious-horror-of-geocities-with-this-we-5983574
* https://oneterabyteofkilobyteage.tumblr.com/
* [90s retro websign](https://www.google.com/search?q=90s+retro+design+web&tbm=isch&ved=2ahUKEwjjquCE6e7nAhVDk54KHVD9BwwQ2-cCegQIABAA&oq=90s+retro+design+web&gs_l=img.3...5826.6340..6502...0.0..0.62.177.3......0....1..gws-wiz-img.fbGmWxsdllk&ei=IC9WXuOaGMOm-gTQ-p9g&bih=952&biw=1920)
* [pixel artists](https://www.google.com/search?q=pixel+artist&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiOh_qU6u7nAhVNKDQIHXgyAhMQ_AUoAXoECBAQAw&biw=1920&bih=939)

**Comment by serapath** [comment]
## `@todo`
* [see here](https://github.com/playproject-io/datdot/issues/2#issue-548286270)
---

https://xd.adobe.com/view/e7a505be-1e7e-4b5e-4d18-866825368100-9194/screen/0d565c1a-9c5d-4771-923e-473fb4a70e04/landing-page-wireframe-desktop

# "START MENU"
```
* [APPEARANCE](datdot://softwaremanager/datdotOS#settings/theme)
* [MISC] >
    * Coding Game
    * Pacman
* --------------------------------------------
* SOFTWARE MANAGER
* RUN (**input field**) > 
   * Pacman
   * Coding Game
   * File Explorer
   * Datdot Docs
```

----

### SOFTWARE MANAGER
1. List of all installed Programs
   - Option to Uninstall Programs
   * e.g. Pacman, Coding Game
2. List of available Installers
   * e.g. Datdot
3. Click on **single program** it opens the <program>.install (e.g. datdot.install)
   => opens it e.g. as part of the SOFTWAR MANAGER

### RUN (concept brainstorming)
typing: e.g.
```
      [ Pacm..  ]        >  Pacman Application
                            Pacman Documentation
                            Pacman Settings

      [ Pacm  Set.. ]    >  Pacman Settings
```
----
#### EXAMPLE - `DATDOT Desktop.install`
* Welcome Splash Screen
    * Title
    * Description
    * Download/Install/Uninstall/Update Button
        * Select Version
* Documentation (select Version)
* Settings (only active after installation) (select Version)
* News (e.g. see VScode welcome screen) (via NOTIFICATIONS)
   * e.g. Updates/Releases/Changelog
   * e.g. Blog Posts
* About
    * repository
    * license
* Support Chat


----
#### Implementation of landingpage (datdot OS) idea
```html
<!doctype html>
<html>
  <head><meta charset="utf-8"></head>
  <body><script>
if (localStorage.softwaremanager) {
  const installed = JSON.parse(localStorage.softwaremanager).installed
  START(installed)
} else {
  const installed = [
    'CodingGame',
    'Pacman',
    'DATDOT Desktop',
  ]
  localStorage.softwaremanager = JSON.stringify({
    installed: installed,
    available: [
      'DATDOT'
    ]
  })
  START(installed)
}
function START (installed) {
  installed.forEach(software => {
    if (localStorage[software]) {
      execute(localStorage[software])
    } else {
      const data = fetch(software)
      localStorage[software] = data
      execute(data)
    }
  })
}
  </script></body>
</html>
```

**Comment by fionataeyang** [comment]
### Workflow/Userflow reference
https://cbalmes2.files.wordpress.com/2014/08/baldor-online-fulfillment-process-11-4-2014.pdf
https://dribbble.com/shots/2616274-Information-Architecture-for-Zyksa-com/attachments/522373
https://chrisbalmes.work/portfolio/baldor-foods/
https://cbalmes2.files.wordpress.com/2014/08/new_page_1.png
https://dribbble.com/shots/9368926-IA-Flow-Chart/attachments/1397876?mode=media
https://dribbble.com/shots/3438926-Nest-Redesign-User-Flow-Diagram

**Comment by serapath** [comment]
**Idea about "system manager" vs. "package manager":**
1. package manager works how the wireframes currently show it
2. **datdot-org system** manager is something we have to decide about
  1. it cannot be uninstalled or removed
  2. it has all the features and information like a normal "package installer"
    * e.g. intro, docs, news, about, support chat, `supply tree`, ...
  3. to click `supply tree` it shows: e.g. clock, appearance, package manager, ...
    * "supply tree items" cannot be uninstalled or removed
    * to click e.g. "clock" item, will open "package installer view" for clock package
    * if you click "back" from a "supply tree item" you return to parent item (e.g. **datdot-org system**)

---

* [slides about how dat works](https://slides.com/serapath/ethberlin-workshop#/6/1)
* [details about how dat works](https://datprotocol.github.io/how-dat-works/)
* [issue about package manager download details](https://github.com/playproject-io/datdot-research/issues/4#event-3021992145)
![sketch2](https://imgur.com/xo739zm.png)
![sketch1](https://imgur.com/3YmMCMF.png)
![sketch3](https://i.imgur.com/LtVrkTl.png)

**Comment by fionataeyang** [comment]
## `@issue`
1. DatDot.org owns about, documentation, settings, news, support chat, supply tree
It is only removed information, becoz information is should be in the documentation, and it is not able to install or download, so this one is not exist. Thus, I feel DatDot.org can click from DatDot logo. 
I never feel it should be as same as package manager, becoz DatDot is the core of the whole system, so it is not part of package manager. Package manager is part of DatDot.org. It must to be easy to recognize for the user to see the different interface between package manager. 
![image](https://user-images.githubusercontent.com/9526525/82121377-167c1600-97bf-11ea-9d97-a6d690741c40.png)

2. Add other package from link 
![image](https://user-images.githubusercontent.com/9526525/82121388-34e21180-97bf-11ea-95cc-09b791522c6c.png)

This is a not confirm behavior, becoz it is only fit for one link for each time to add package.
Here is the scenario via `npm`.
When I wanna use `npm install` and use the multiple way to install the different packages.
I can use `npm install bel csjs-inject --save` to execute and automatically install the packages.
The problem I feel that search input to switch to paste the link, but only add one card into the below, and the user needs to click install to download it for sure.
![image](https://user-images.githubusercontent.com/9526525/82121516-45df5280-97c0-11ea-89ac-8d3d5aae4ed6.png)

I feel it is not intuitive and unfriendly for the user to use this input.

Is it possible to edit like an array instead of not just paste a link.
For example:

[ { dat://xxxxxxxxxxxxxxxxxxx, true}, {dat://xxxxxxxxxxxxxxxxxxx, false}]
![image](https://user-images.githubusercontent.com/9526525/82121702-a02ce300-97c1-11ea-90ad-d6f5d74af5a0.png)

Here's true means allow to auto directly download when add, false is opposite about not auto download, just only add a new card.
This is a feeling I have the issue when I reinstall VSCode, and lost every plugins, I have to search again, and manually install them all via each.

**Comment by ninabreznik** [comment]
1. I feel the same about the datdot.org as a package. I wonder what do you think if datdot.org package would open directly when you click the datdot logo? And the software manager would open all the other apps.
So, the datdot logo opens directly the datdot.org package. Software manager icon opens the preview of other apps and when you click on one it opens that particular package.

Then we don't need a system manager, because all the dependencies of the datdot.org package are listed in the supply tree and can be opened from there.

2. I actually like the idea of adding and installing in one step since this is most typical need. And if people don't want to have it installed, they can still manually uninstall it after it is installed, they can cancel it (this would probably stop the instal & remove the whole package), plus, we can maybe somewhere in datdot.org settings or software manager settings add an option uncheck the autoinstall.

**Comment by fionataeyang** [comment]
1. This is how I feel when click DatDot logo
![image](https://user-images.githubusercontent.com/9526525/82123836-16374700-97ce-11ea-879d-71baff7a4cb0.png)

I think there is no system manager, the package manager's icon can be appearance in the settings(not sure the correct name), also appearance icon too.

This was I've thinking to move the appearance to settings, but I think can change the interface to put the icons to here. (The icons include appearance and package manager)
![image](https://user-images.githubusercontent.com/9526525/82123860-3cf57d80-97ce-11ea-8b6b-002ff5132927.png)

2. So, I will change the interface of DatDot.org settings. It is a settings for the whole system.

**Comment by ninabreznik** [comment]
I am thinking like this. We have a datdot.org package. It has dependencies, listed in the supply tree.
The dependencies are: clock, software manager, appearance etc.

If you go under datdot.org package / settings, you find settings for datdot.org + settings for each dependency, all together. BUT you can also go to the supply tree and click for example appearence which opens appearance package. There you also have the settings, but only for the appearance.

This means, you can change appearance directly from the datdot.org package settings & from the appearance package settings.

Both are always synchronized.

**Comment by fionataeyang** [comment]
Oh..I have no idea about the supply tree for DatDot.org. Would you give me the correct list of it?
And this is settings in DatDog.org that I've just updated.
![image](https://user-images.githubusercontent.com/9526525/82124433-99a66780-97d1-11ea-8b34-898b1274e883.png)

**Comment by ninabreznik** [comment]
I think it's these 3 yes, can't think of any other now. Is clock and language part of task bar?

I like this approach, but just want to ask. If you click here for example appearance, it opens appearance package directly on the settings tab?

**Comment by serapath** [comment]
Thank you @fionataeyang  for the issue and nice description.

my thoughts are:
**First - regarding the maybe easier one => (2.):**
I agree with you. Your suggestion to solve it sounds great.
I remember for smartcontract codes, we also had a more sophesticated input field that allowed to write a single word or link, but also to write multiple links - not to forget the sophesticated generated input form that smartcontract-ui was or is. Let's try it :-)

**Second - regarding (1.):**
I think it all boils down to misunderstandings rather then real differences in perception.

We have the UI/UX side of things.
We also have the repos & developer & maintainance side of things and both need to work to give the best possible UI/UX but not forget what it means in terms of building and maintaining it on the implementation side.

If you think nina's proposal above makes sense - I think I can agree with that.

---
**Additionally: Regarding the supply tree (e.g. of datdot-os)**
 We need the implementation and logic in place so that it auto-changes what shows in the supply tree every time we update the supply tree / dependencies.
That is the whole point, so that we don't need to know at this moment what will be exactly shown there. If we list a few items as examples (e.g. clock, pacman, appearance, ...) that's ok to get the idea and when we come to the final implementation, whatever we figured out then, will be automatically displayed there, no matter if it is 2 or 10 items.
I perceive this to be the goal so we don't need to now already know for all future :-)

**Comment by fionataeyang** [comment]
# @issue2

I changed the search and add button behavior. I hope to avoid the user to click dropdown to find the options. This was an inspiration from other website. Plus we don't have much settings to do with auto download. Therefore, I think put it under add input field to make a checkbox, the user doesn't need to go to settings page to decide auto or not auto download. This for me is more convenient and easier to notice.

## Search
![image](https://user-images.githubusercontent.com/9526525/82322611-5e8e7900-9a09-11ea-846f-05b7e381edcc.png)
## Add new
![image](https://user-images.githubusercontent.com/9526525/82322664-76fe9380-9a09-11ea-86b2-8e4cf890c005.png)

Question1:
I make 3 ways to add the new address. Which one do you prefer the most?
### Demo1
Add multiple address like search selector input field. It can add many address for one time when click the add button. The heavy color is the behavior when the user hover it to present all characters. Without background color is current typing. They are all separate when the user type ```,``` and use ```space```  keyboard like write a email address in Gmail or others.
![image](https://user-images.githubusercontent.com/9526525/82322788-a90ff580-9a09-11ea-9299-c0f614935241.png)

### Demo2
Add multiple address but keep the address length to display
![image](https://user-images.githubusercontent.com/9526525/82322804-b0cf9a00-9a09-11ea-9600-ae5bf53879eb.png)

### Demo3
Add one address, and the package can display the picture and the information. This idea came from twitter and facebook's post. I wonder is it possible to make? 
This idea is more like the user can check download the right package before add. To recognize logo and team's name.
![image](https://user-images.githubusercontent.com/9526525/82322822-b75e1180-9a09-11ea-9972-b337325869f4.png)

**Comment by fionataeyang** [comment]
@ninabreznik 
Clock and Language would be the icons in Settings page as well. I will add them into there that I forgot.

I update Settings.
![image](https://user-images.githubusercontent.com/9526525/82328072-fb551480-9a11-11ea-97fa-681fd15e4467.png)


Appearance would be displaying in Settings page. :) I've already changed the behavior, and let the user learning how to find the appearance as well. I also keep Appearance icon on the task bar.

**Comment by fionataeyang** [comment]
@serapath 
For supply tree, I think I would only make the template which means no matter how much items inside, they will be following the style to display.
When you both confirmed it then I won't change too much there.

For your previous question with second,
1. I don't know which part should be maintain, I just do my best way to think about UIUX and also make it possible to maintain as well, for example package list and package information.
2. I've already some experiences with smartcontract.codes and smartcontract-UI to make themes, and those are already enough to you and Nina understand how to maintain the styles as well.

This was a landing page...not a platform, but it is now.
Every platform has a rule to define to require everyone follow it as well.

---------------------------------------------------------
# @issue
I have feeling that supply tree cannot customize to design, it should be using d3.js to make the tree. There would be more and more packages in our supply tree or others. I'm not sure the design would be fit in the future. And I realize it is really difficult to make a tree responsive for fitting the different screen size. This is why I think it should be using d3.js or other tools. 
This is an issue when the width space is not enough to display.
![image](https://user-images.githubusercontent.com/9526525/82329847-82a38780-9a14-11ea-9e17-f3e30a17793c.png)


### D3.js demo
https://bl.ocks.org/d3noob/8326869
![image](https://user-images.githubusercontent.com/9526525/82329984-c3030580-9a14-11ea-8656-db6feb48ae89.png)

**Comment by serapath** [comment]
**issue**
* [`playproject-io.github.io#14` package manager input field & related](https://github.com/playproject-io/playproject-io.github.io/issues/14)
