### ISSUE TITLE
datdot default apps

### ISSUE THREAD

**Issue by serapath** [datdotorg/website#41]
## `@todo`
* [ ] coding game (wizardamigos app?)
* [ ] pacman (or adapt some existing open source equivalent)
* [ ] [`datdot#39` datdot app: settings json editor](https://github.com/playproject-io/datdot/issues/39)
* [ ] [`datdot#40` datdot app: documentation viewer](https://github.com/playproject-io/datdot/issues/40)
* [ ] [`datdot#45` overflow funding model](https://github.com/playproject-io/datdot/issues/45)

---

1. datdot exposing "dat stuff" to browsers
2. and the little "operating system desktop" style website we are making
3. will have a "Software Manager"  to install apps (=widgets) into that website
4. whoever makes that app will receive datdot from the users according to our funding mechanics, which will include contributors/maintainers/dependencies of those apps
