### ISSUE TITLE
package manager

### ISSUE THREAD

**Issue by serapath** [datdotorg/website#52]
## `@todo`
* [ ] implement software manager according to datdot landingpage concept
* [ ] include a donate button to apps in software manager (DatDot) for each app
* [ ] [`datdot#56 package manager - custom settings editor](https://github.com/playproject-io/datdot/issues/56)

---

software manager app icons to show version and indicator if latest or other version or if updates available
* https://nixos.org/
