### ISSUE TITLE
OpenWindow issue report

### ISSUE THREAD

**Issue by fionataeyang** [datdotorg/website#58]
# `@todo`
## Window
- [x] minimize and maximize the window
- [x] Close window
- [X] Responsive design
- [x] Default opening (DatDot.install opening)
- [ ] Drag and move

### @issue
1. drag and move
It is difficult to write the code and implementing. Not familiar it. Maybe can try to use the plugin to support.
2. Default opening
This is related to the structor of data via json loaded to check which app is opening.
