### ISSUE TITLE
datdot-os

### ISSUE THREAD

**Issue by serapath** [datdotorg/website#59]
## `@todo`
* [ ] [`datdot#2` datdot project landing page](https://github.com/playproject-io/datdot/issues/2)
* [ ] [`datdot#58` OpenWindow issue report](https://github.com/playproject-io/datdot/issues/58)
* [ ] [`datdot#57` Markdown issue report](https://github.com/playproject-io/datdot/issues/57)
* [ ] make new repo and transition datdot once it works

---
**goal:**
transition datdot repo into a datdot-os module repo and make datdot a single opinionated generic installation of it
