### ISSUE TITLE
multichain management

### ISSUE THREAD

**Issue by serapath** [datdotorg/website#60]
## `@todo`
* [ ] start a testnet
  * [`datdot#54` make testnet and turn it into real, but experimental network over time](https://github.com/playproject-io/datdot/issues/54)
* [ ] start a wizardamigos mainnet (expect chaos)
  * [`wizardamigos/aybabtu#1` roadmapping](https://github.com/wizardamigos/aybabtu/issues/1)
* [ ] think about exchange mechanisms
* [ ] think about update strategies
* [ ] launch datdot mainnet

---
