### ISSUE TITLE
backlog

### ISSUE THREAD

**Issue by serapath** [datdotorg/website#70]
## `@todo`
* [x] [`datdot#1` milestone1: 2019.08.23 - 13.07.2020](https://github.com/playproject-io/datdot/issues/1)
* [ ] [`datdot#71` roadmapping](https://github.com/playproject-io/datdot/issues/71)
* [ ] [`datdot#69` backlog for milestone 3](https://github.com/playproject-io/datdot/issues/69)
* [ ] [`datdot-tcir#1` roadmapping](https://github.com/playproject-io/datdot-tcir/issues/1)

---
