### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by ninabreznik** [datdotorg/website#72]
## `@todo`
- [ ] engage folx on forums ala SloTech
- [ ] Max science contacts
- [ ] biotech wizard interviews
- [ ] language translations [see here](https://twitter.com/feross/status/1390779802861248514)
- [ ] drum n bass archives
- [ ] mags like joker and monitor PR articles
- [ ] make a template for communities to build their own data app - enables browsing and downloading data (retro games, collectibes, smart cotract codes...)

**Comment by serapath** [comment]
Jscad to be used on datdot (3d model registry)

**Comment by serapath** [comment]
* [ ] make a runtime account, e.g. like bun or deno and tweet short example code snippets with a tweet sized description and link to open a website to play around and execute that code snippet
