### ISSUE TITLE
spec: write down p2p hosting idea

### ISSUE THREAD

**Issue by serapath** [datdotorg/website#8]
## `@todo`
* [x] proof of concept `substrate`
* [x] proof of concept `polkadotjs`
* [x] [initial datdot spec `v0.0.0-initial@2019-08-23`](https://github.com/playproject-io/datdot-research/blob/master/spec/v0.0.0-initial%402019-08-23.md)

---
